export const SAMPLE_ORDERS = [
  {
    order_date: '2026-04-21',
    category: '모자',
    product_code: 'WLS46V9X',
    product_name: 'UV 프로텍션 와이드 바이저 카옐리',
    image_url: null,
    color_code: 'BK', color_name: '블랙',
    order_qty: 2000,
    factory: '중국 소니아공장',
    factory_payment_type: '계약금선납',
    contract_deposit_paid: false,
    delivery_destination: '주희물류',
    expected_delivery_date: '2026-07-01',
    status: '생산중',
    materials: { '원단': false, '메인라벨': false, '케어라벨': false, '행택': false, '지퍼백': false },
    warehouse_qty: 0, memo: '',
  },
  {
    order_date: '2026-04-21',
    category: '모자',
    product_code: 'WLS46V9X',
    product_name: 'UV 프로텍션 와이드 바이저 카옐리',
    image_url: null,
    color_code: 'DP', color_name: '다크핑크',
    order_qty: 300,
    factory: '중국 소니아공장',
    factory_payment_type: '계약금선납',
    contract_deposit_paid: false,
    delivery_destination: '주희물류',
    expected_delivery_date: '2026-07-01',
    status: '생산중',
    materials: { '원단': false, '메인라벨': false, '케어라벨': false, '행택': false, '지퍼백': false },
    warehouse_qty: 0, memo: '',
  },
  {
    order_date: '2026-04-20',
    category: '모자',
    product_code: 'GKS35C8H',
    product_name: '그린라벨 워셔블 반다나 캡 볼로스',
    image_url: null,
    color_code: 'DGY', color_name: '다크그레이',
    order_qty: 300,
    factory: '하이호프',
    factory_payment_type: '바로생산',
    contract_deposit_paid: false,
    delivery_destination: '주희물류',
    expected_delivery_date: '2026-04-28',
    status: '생산중',
    materials: { '원단': true, '메인라벨': true, '케어라벨': false, '행택': false, '지퍼백': false },
    warehouse_qty: 0, memo: '납기 임박 주의',
  },
]
